name: uk259
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - scipy
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - tensorflow
  - jupyter
  - seaborn
  - ipykernel
  - ipympl
  - pydot 
  - graphviz 
  - nodejs=16.*